# Builds the MAUI Android application

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  targetFramework: 'net8.0-android34.0'

steps:

- task: DownloadSecureFile@1
  name: androidKeystore
  displayName: 'Download Android Keystore'
  inputs:
    secureFile: 'android_keystore.keystore'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: './KChristmas.Android/KChristmas.Android.csproj'
    arguments: '-f ${targetFramework} -c ${buildConfiguration} -o ${outputDirectory}/ -p:AndroidKeyStore=true -p:AndroidSigningKeyStore=${androidKeystore.secureFilePath} -p:AndroidSigningKeyAlias=2018-and-beyond -p:AndroidSigningKeyPass=${keystore_password} -p:AndroidSigningStorePass=${keystore_password}'

- task: PublishBuildArtifacts@1
  displayName: "Publish output directory"
  inputs:
    PathtoPublish: '$(outputDirectory)'
    ArtifactName: 'android-apk'
    publishLocation: 'Container'